--------------------------------------------------------
--  File created - Tuesday-November-02-2021   
--------------------------------------------------------
DROP TABLE "IHEB"."ACHETER" cascade constraints;
DROP TABLE "IHEB"."CLIENTS" cascade constraints;
DROP TABLE "IHEB"."CREER" cascade constraints;
DROP TABLE "IHEB"."EMPLOYES" cascade constraints;
DROP TABLE "IHEB"."EQUIPEMENTS" cascade constraints;
DROP TABLE "IHEB"."MAINTENIR" cascade constraints;
DROP TABLE "IHEB"."PRODUITS" cascade constraints;
DROP TABLE "IHEB"."PUBLICITES" cascade constraints;
DROP TABLE "IHEB"."RESERVER" cascade constraints;
DROP TABLE "IHEB"."SERVICES" cascade constraints;
--------------------------------------------------------
--  DDL for Table ACHETER
--------------------------------------------------------

  CREATE TABLE "IHEB"."ACHETER" 
   (	"QUANTITE" NUMBER(*,0), 
	"CIN_C" NUMBER, 
	"CODE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENTS
--------------------------------------------------------

  CREATE TABLE "IHEB"."CLIENTS" 
   (	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"CIN_C" NUMBER, 
	"ADRESSE_MAIL" VARCHAR2(20 BYTE), 
	"TEL" NUMBER, 
	"SEXE" VARCHAR2(6 BYTE), 
	"MONTANT_DEPENSER" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "IHEB"."CLIENTS"."SEXE" IS '"0" pour homme et "1" pour femme';
--------------------------------------------------------
--  DDL for Table CREER
--------------------------------------------------------

  CREATE TABLE "IHEB"."CREER" 
   (	"ID_P" NUMBER, 
	"CIN_E" NUMBER, 
	"DATE_CREATION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYES
--------------------------------------------------------

  CREATE TABLE "IHEB"."EMPLOYES" 
   (	"CIN_E" NUMBER, 
	"TEL" NUMBER, 
	"EMAIL" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"FONCTION" VARCHAR2(20 BYTE), 
	"SEXE" VARCHAR2(6 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE), 
	"SALAIRE" FLOAT(126), 
	"AGE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EQUIPEMENTS
--------------------------------------------------------

  CREATE TABLE "IHEB"."EQUIPEMENTS" 
   (	"ID" NUMBER, 
	"MARQUE" VARCHAR2(20 BYTE), 
	"ETAT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MAINTENIR
--------------------------------------------------------

  CREATE TABLE "IHEB"."MAINTENIR" 
   (	"CIN_E" NUMBER, 
	"ID_E" NUMBER, 
	"DATE_REPARTITION" DATE, 
	"TYPE_DEFAUT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUITS
--------------------------------------------------------

  CREATE TABLE "IHEB"."PRODUITS" 
   (	"CODE" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRIX" FLOAT(126), 
	"QUALITE" VARCHAR2(20 BYTE), 
	"STOCK" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PUBLICITES
--------------------------------------------------------

  CREATE TABLE "IHEB"."PUBLICITES" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"DATEP" DATE, 
	"PRIX" FLOAT(126), 
	"DESCRIPTION" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESERVER
--------------------------------------------------------

  CREATE TABLE "IHEB"."RESERVER" 
   (	"ID" NUMBER, 
	"CIN_E" NUMBER, 
	"CIN_C" NUMBER, 
	"DATEP" DATE, 
	"DATE_HEURE_R" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SERVICES
--------------------------------------------------------

  CREATE TABLE "IHEB"."SERVICES" 
   (	"ID" NUMBER, 
	"PRIX" FLOAT(126), 
	"DATE_PASSAGE" DATE, 
	"DATE_LIVRAISON" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into IHEB.ACHETER
SET DEFINE OFF;
REM INSERTING into IHEB.CLIENTS
SET DEFINE OFF;
REM INSERTING into IHEB.CREER
SET DEFINE OFF;
REM INSERTING into IHEB.EMPLOYES
SET DEFINE OFF;
REM INSERTING into IHEB.EQUIPEMENTS
SET DEFINE OFF;
REM INSERTING into IHEB.MAINTENIR
SET DEFINE OFF;
REM INSERTING into IHEB.PRODUITS
SET DEFINE OFF;
REM INSERTING into IHEB.PUBLICITES
SET DEFINE OFF;
REM INSERTING into IHEB.RESERVER
SET DEFINE OFF;
REM INSERTING into IHEB.SERVICES
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index CINC_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IHEB"."CINC_PK" ON "IHEB"."CLIENTS" ("CIN_C") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RESERVER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IHEB"."RESERVER_PK" ON "IHEB"."RESERVER" ("CIN_E", "CIN_C", "ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IDACHETER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IHEB"."IDACHETER_PK" ON "IHEB"."ACHETER" ("CIN_C", "CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ID_MAINTENIR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IHEB"."ID_MAINTENIR_PK" ON "IHEB"."MAINTENIR" ("CIN_E", "ID_E") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IDS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IHEB"."IDS_PK" ON "IHEB"."SERVICES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IDEQUIP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IHEB"."IDEQUIP_PK" ON "IHEB"."EQUIPEMENTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_EMPL
--------------------------------------------------------

  CREATE UNIQUE INDEX "IHEB"."PK_EMPL" ON "IHEB"."EMPLOYES" ("CIN_E") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CREER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IHEB"."CREER_PK" ON "IHEB"."CREER" ("ID_P", "CIN_E") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRODUITS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IHEB"."PRODUITS_PK" ON "IHEB"."PRODUITS" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PRODUITS
--------------------------------------------------------

  ALTER TABLE "IHEB"."PRODUITS" ADD CONSTRAINT "PRODUITS_PK" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IHEB"."PRODUITS" MODIFY ("CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CREER
--------------------------------------------------------

  ALTER TABLE "IHEB"."CREER" ADD CONSTRAINT "ID_CREER_PK" PRIMARY KEY ("ID_P", "CIN_E")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IHEB"."CREER" MODIFY ("ID_P" NOT NULL ENABLE);
  ALTER TABLE "IHEB"."CREER" MODIFY ("CIN_E" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ACHETER
--------------------------------------------------------

  ALTER TABLE "IHEB"."ACHETER" ADD CONSTRAINT "IDACHETER_PK" PRIMARY KEY ("CIN_C", "CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IHEB"."ACHETER" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "IHEB"."ACHETER" MODIFY ("CIN_C" NOT NULL ENABLE);
  ALTER TABLE "IHEB"."ACHETER" MODIFY ("QUANTITE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MAINTENIR
--------------------------------------------------------

  ALTER TABLE "IHEB"."MAINTENIR" ADD CONSTRAINT "ID_MAINTENIR_PK" PRIMARY KEY ("CIN_E", "ID_E")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IHEB"."MAINTENIR" MODIFY ("ID_E" NOT NULL ENABLE);
  ALTER TABLE "IHEB"."MAINTENIR" MODIFY ("CIN_E" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENTS
--------------------------------------------------------

  ALTER TABLE "IHEB"."CLIENTS" ADD CONSTRAINT "CINC_PK" PRIMARY KEY ("CIN_C")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IHEB"."CLIENTS" MODIFY ("CIN_C" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYES
--------------------------------------------------------

  ALTER TABLE "IHEB"."EMPLOYES" ADD CONSTRAINT "PK_EMPL" PRIMARY KEY ("CIN_E")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SERVICES
--------------------------------------------------------

  ALTER TABLE "IHEB"."SERVICES" ADD CONSTRAINT "IDS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IHEB"."SERVICES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EQUIPEMENTS
--------------------------------------------------------

  ALTER TABLE "IHEB"."EQUIPEMENTS" ADD CONSTRAINT "IDEQUIP_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IHEB"."EQUIPEMENTS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESERVER
--------------------------------------------------------

  ALTER TABLE "IHEB"."RESERVER" ADD CONSTRAINT "RESERVER_PK" PRIMARY KEY ("CIN_E", "CIN_C", "ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IHEB"."RESERVER" MODIFY ("CIN_C" NOT NULL ENABLE);
  ALTER TABLE "IHEB"."RESERVER" MODIFY ("CIN_E" NOT NULL ENABLE);
  ALTER TABLE "IHEB"."RESERVER" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ACHETER
--------------------------------------------------------

  ALTER TABLE "IHEB"."ACHETER" ADD CONSTRAINT "CINC_FK" FOREIGN KEY ("CIN_C")
	  REFERENCES "IHEB"."CLIENTS" ("CIN_C") ENABLE;
  ALTER TABLE "IHEB"."ACHETER" ADD CONSTRAINT "CODEP_FK1" FOREIGN KEY ("CODE")
	  REFERENCES "IHEB"."PRODUITS" ("CODE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CREER
--------------------------------------------------------

  ALTER TABLE "IHEB"."CREER" ADD CONSTRAINT "CIN_E_FK4" FOREIGN KEY ("CIN_E")
	  REFERENCES "IHEB"."EMPLOYES" ("CIN_E") ENABLE;
  ALTER TABLE "IHEB"."CREER" ADD CONSTRAINT "ID_P_FK2" FOREIGN KEY ("ID_P")
	  REFERENCES "IHEB"."EQUIPEMENTS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MAINTENIR
--------------------------------------------------------

  ALTER TABLE "IHEB"."MAINTENIR" ADD CONSTRAINT "CIN_E_FK1" FOREIGN KEY ("CIN_E")
	  REFERENCES "IHEB"."EMPLOYES" ("CIN_E") ENABLE;
  ALTER TABLE "IHEB"."MAINTENIR" ADD CONSTRAINT "ID_EQUIP_FK2" FOREIGN KEY ("ID_E")
	  REFERENCES "IHEB"."EQUIPEMENTS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESERVER
--------------------------------------------------------

  ALTER TABLE "IHEB"."RESERVER" ADD CONSTRAINT "CIN_C_FK1" FOREIGN KEY ("CIN_C")
	  REFERENCES "IHEB"."CLIENTS" ("CIN_C") ENABLE;
  ALTER TABLE "IHEB"."RESERVER" ADD CONSTRAINT "CIN_E_FK3" FOREIGN KEY ("CIN_E")
	  REFERENCES "IHEB"."EMPLOYES" ("CIN_E") ENABLE;
  ALTER TABLE "IHEB"."RESERVER" ADD CONSTRAINT "IDS_FK2" FOREIGN KEY ("ID")
	  REFERENCES "IHEB"."SERVICES" ("ID") ENABLE;
